logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  boot:
    admin:
      client:
        url: http://localhost:9000
  zipkin:
    base-url: http://localhost:12000
    sender: web
  sleuth:
    sampler:
      probability: 1.0

management: #actuator
  endpoints:
    enable: true
    web:
      exposure:
        include: "*"