spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      database: piggymetrics
      min-connections-per-hos: 10
      max-connections-per-host: 100
      threads-allowed-to-block-for-connection-multiplier: 5

server:
  port: 10000

management: #actuator
  endpoints:
    enable: true
    web:
      exposure:
        include: "*"